// THE WORKER'S COPY OF THE SHARE CODE, generated from the page's part so the
// two read one grammar. The part is copied verbatim; what the part asks of its
// host (`shareIndex`, `evoPrefixFor`, `boardRivenName`) is bound to whatever
// `useShareHost` is handed.
//
//   node scripts/gen_worker_codec.mjs           # write worker/share_codec.js
//   node scripts/gen_worker_codec.mjs --check   # fail if it is stale (CI)
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PART = "web/src/static/app/29-share-codec.js";
const OUT = "worker/share_codec.js";

const body = readFileSync(resolve(ROOT, PART), "utf8");
const text = `// GENERATED by scripts/gen_worker_codec.mjs from ${PART} — never edit.
let HOST = null;
/// The host the codec reads from: \`{ index, evoPrefixFor, rivenName }\`.
export function useShareHost(host) { HOST = host; }
const shareIndex = () => HOST.index;
const evoPrefixFor = (weapon) => HOST.evoPrefixFor(weapon);
const boardRivenName = (riven) => HOST.rivenName(riven);

${body}
export { decodeShare };
`;

const out = resolve(ROOT, OUT);
if (process.argv.includes("--check")) {
  const now = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (now.replace(/\r\n/g, "\n") !== text) {
    console.log(`FAIL  ${OUT} is not ${PART} — run: node scripts/gen_worker_codec.mjs`);
    process.exit(1);
  }
  console.log(`ok  ${OUT} is the page's codec`);
} else {
  writeFileSync(out, text);
  console.log(`wrote ${OUT}`);
}
