// THE WORKERS' COPIES OF THE PAGE'S SHARED PARTS, generated so a worker and the
// page run one piece of code. Each part is copied verbatim; what it asks of its
// host is bound or exported by the lines around it.
//
//   node scripts/gen_worker_parts.mjs           # write every copy
//   node scripts/gen_worker_parts.mjs --check   # fail if one is stale (CI)
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

const PARTS = [
  {
    // The share code: the page that writes a link and the edge that previews it
    // read one grammar. The codec asks `shareIndex`, `evoPrefixFor` and
    // `boardRivenName` of its host, bound to whatever `useShareHost` is handed.
    part: "web/src/static/app/29-share-codec.js",
    out: "worker/share_codec.js",
    head: `let HOST = null;
/// The host the codec reads from: \`{ index, evoPrefixFor, rivenName }\`.
export function useShareHost(host) { HOST = host; }
const shareIndex = () => HOST.index;
const evoPrefixFor = (weapon) => HOST.evoPrefixFor(weapon);
const boardRivenName = (riven) => HOST.rivenName(riven);
`,
    tail: "export { decodeShare };\n",
  },
  {
    // The headless queries: the MCP server answers from the table the door
    // reads (docs/AGENT.md §"Headless queries"). A query is handed its host.
    part: "web/src/static/app/87-headless.js",
    out: "mcp/headless.js",
    head: "",
    tail: "export { HEADLESS_ABOUT, HEADLESS_QUERIES, HEADLESS_RETIRED, headlessCheckArgs, headlessSchema, headlessNo, headlessToolName, headlessUnknown,\n  headlessSeat, headlessStateAxes, headlessWeapon, headlessWeaponPath, rivenStatNames, rivenStatNameEn, ocrFold, rivenQuery };\n",
  },
];

let stale = 0;
for (const { part, out, head, tail } of PARTS) {
  const body = readFileSync(resolve(ROOT, part), "utf8");
  const text = `// GENERATED by scripts/gen_worker_parts.mjs from ${part} — never edit.\n${head}\n${body}\n${tail}`;
  const path = resolve(ROOT, out);
  if (process.argv.includes("--check")) {
    const now = existsSync(path) ? readFileSync(path, "utf8") : "";
    if (now.replace(/\r\n/g, "\n") !== text) {
      console.log(`FAIL  ${out} is not ${part} — run: node scripts/gen_worker_parts.mjs`);
      stale++;
    } else {
      console.log(`ok  ${out} is ${part}`);
    }
  } else {
    writeFileSync(path, text);
    console.log(`wrote ${out}`);
  }
}
if (stale) process.exit(1);
